// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.doopp.reactor.guice.test.proto.hello;

public interface HelloOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Hello)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
